language: python
python:
- '2.7'
before_install:
  - sudo apt-get install python-dev
install:
  - pip install molecule
before_script:
script:
  - molecule lint
  - molecule dependency
  - molecule syntax
after_success:
after_failure:
after_script:
