---
# tasks for launching the discourse container
- name: restart docker
  become: true
  service:
    name: docker
    state: restarted
  changed_when: false

#  (destroy old, bootstrap, start new)
- name: rebuild the app
  become: true
  become_user: "{{ discourse_user }}"
  raw: "{{ discourse_path }}/launcher rebuild app"
  asynch: 120
  poll: 10
