---
# tasks for launching the discourse container
- name: restart docker
  become: true
  service:
    name: docker
    state: restarted
  changed_when: false

- name: There's really nothing wrong with devicemapper
  replace:
    path: "{{ discourse_path }}/launcher"
    after:
    regexp: aufs\|btrfs\|zfs\|overlay\|overlay2
    replace: aufs|btrfs|zfs|overlay|overlay2|devicemapper

#  (destroy old, bootstrap, start new)
- name: rebuild the app
  become: true
  become_user: "{{ discourse_user }}"
  raw: "{{ discourse_path }}/launcher rebuild app"
  asynch: 120
  poll: 10
