---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
platforms:
  - name: instance
    image: CentOS7
    flavor: m1.medium
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0012
        - ANSIBLE0004
      force-color: true
    enabled: false
scenario:
  name: openstack-unict
verifier:
  name: testinfra
  lint:
    name: flake8
